- name: Copy Config File
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml

- name: Create Folder - {{ item.job_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{ item.job_name }}"
    password: admin123
    url: http://172.31.28.50:8080
    user: admin